In [1]:
# Biblioteca numpy

In [5]:
pip install numpy # instalando a biblioteca

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 6.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 11.0 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.6 MB 11.3 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.6 MB 11.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.8 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np # Importando a biblioteca e dando, 'as', um apelido a ela, 'np'.

In [7]:
x = np.array([1,5,9]) # Matriz de 1 linha e 3 colunas
print(x)

[1 5 9]


In [11]:
y = np.array([(1,2,3),(7,8,9),(4,5,6)]) # Matriz de 3 linhas e 3 colunas
print(y)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [13]:
z = np.zeros((3,5))# Matriz de 3 linha e 5 colunas
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
