In [1]:
import pandas as pd
import numpy as np

In [2]:
pares = pd.Series([2,4,6,8,42,60]) # Matriz unidimencional
print(pares)

0     2
1     4
2     6
3     8
4    42
5    60
dtype: int64


In [3]:
impares = np.array([1,3,5,7,9,43,101])  # Matriz unidimencional
print(impares)

[  1   3   5   7   9  43 101]


In [4]:
primos = np.array([(2,3,5,7),(11,13,17,19)]) # Duas Matriz é bidimensional, esse tipo de estrutura só aceita no Numpy
print(primos)

[[ 2  3  5  7]
 [11 13 17 19]]


In [5]:
# tentando usar o pandas para lê uma matriz bidimensional
sequencia = pd.Series(primos)
print(sequencia)

ValueError: Data must be 1-dimensional, got ndarray of shape (2, 4) instead

In [6]:
sequencia1 = pd.Series(pares)
print(sequencia1)

0     2
1     4
2     6
3     8
4    42
5    60
dtype: int64


In [7]:
sequencia2 = pd.Series(impares)
print(sequencia2)

0      1
1      3
2      5
3      7
4      9
5     43
6    101
dtype: int64
